# GPT-3 Model Configuration

model_name: "GPT-3"
variants:
  - name: "125M"
    parameters:
      num_layers: 12
      num_heads: 12
      hidden_size: 768
      seq_length: 2048
      dtype_bytes: 2  # FP16
      
  - name: "350M"
    parameters:
      num_layers: 24
      num_heads: 16
      hidden_size: 1024
      seq_length: 2048
      dtype_bytes: 2
      
  - name: "1.3B"
    parameters:
      num_layers: 24
      num_heads: 16
      hidden_size: 2048
      seq_length: 2048
      dtype_bytes: 2
      
  - name: "6.7B"
    parameters:
      num_layers: 32
      num_heads: 32
      hidden_size: 4096
      seq_length: 2048
      dtype_bytes: 2
      
  - name: "175B"
    parameters:
      num_layers: 96
      num_heads: 96
      hidden_size: 12288
      seq_length: 2048
      dtype_bytes: 2
